modLoader = "lowcodefml"
loaderVersion = "[2,)"
issueTrackerURL = "https://kubejs.com/support?source=rhino&mc=2101&loader=neoforge"
license = "MPL-2.0"

[[mods]]
modId = "rhino"
version = "${version}"
displayName = "Rhino"
authors = "latvian.dev, Mozilla"
description = '''
A fork of Mozilla's Rhino library, modified for use in mods
'''
logoFile = "rhino_logo.png"
modUrl = "https://kubejs.com"
displayURL = "https://kubejs.com"